"""
Video Story Director
Prompt Assembler

Assembles the final Story Director prompt from the prompt modules and the
selected backend.
"""

from builder.constants import (
    PROMPT_DIR,
    BACKENDS_DIR,
    ASSEMBLY_SEQUENCE,
    PROJECT_NAME,
)

from builder.utils import (
    read_text,
    separator,
    timestamp,
)


class Assembler:
    """
    Assembles a production-ready Story Director prompt.
    """

    def __init__(self, backend: str, version: str):
        self.backend = backend
        self.version = version

    def build(self) -> str:
        """
        Build and return the complete prompt.
        """

        sections = []

        sections.append(self._build_header())

        for item in ASSEMBLY_SEQUENCE:

            if item == "__BACKEND__":
                sections.append(self._load_backend())
            else:
                sections.append(self._load_module(item))

        return "\n\n".join(sections).rstrip() + "\n"

    # ---------------------------------------------------------------------

    def _build_header(self) -> str:
        """
        Generate the release header.
        """

        return f"""\
{separator()}
{PROJECT_NAME}

Release Version : {self.version}
Backend         : {self.backend.upper()}
Build Time      : {timestamp()}

This file is automatically generated.
Do not edit this file manually.

{separator()}
"""

    # ---------------------------------------------------------------------

    def _load_module(self, filename: str) -> str:
        """
        Load a prompt module.
        """

        path = PROMPT_DIR / filename

        return read_text(path).strip()

    # ---------------------------------------------------------------------

    def _load_backend(self) -> str:
        """
        Load the selected backend.
        """

        path = (
            BACKENDS_DIR
            / self.backend
            / "backend.md"
        )

        return read_text(path).strip()